* Baklava
@recipe @dessert

** Ingredients
/For Baklava/

- 300 g shelled pistachio nuts, or almonds (or a mixture of both)
- 1.5 tsp ground cinnamon
- 600 g ready-made filo pastry
- 125--150g butter, melted

/For the syrup/

- 300 ml water
- 350 g caster sugar
- 125 ml clear honey
- 1 sticks cinnamon, or 1 tsp ground cinnamon
- 1/2 orange, zest only
- 1 tsp whole cloves
- 1-2 tsp orange flower water, optional

** Method

1. preheat the oven to 180c/gas 4.
2. for the baklava: grind the nuts in a food processor until coarsely ground, then mix in the ground cinnamon.
3. using a soft pastry brush, lightly butter a 24 x 19cm ovenproof dish. gently unfold the filo pastry, covering it immediately with a damp clean tea towel to stop it drying out and cracking.
4. start layering the sheets of filo pastry into the dish, brushing each sheet with melted butter before placing the next layer on top. after six layers, scatter over one-third of the crushed nuts.
5. repeat and add six more layers of filo pastry. butter the top of the last layer and trim off any overlapping pastry with a sharp knife to create a neat edge. cut into small 4-5cm diamonds, making sure the knife goes all the way to the bottom.
6. bake in the middle shelf of the oven for 40--45 minutes, or until golden brown and crisp, reducing the temperature to 170c/gas 3 during cooking if the baklava looks as though it is browning too quickly.
7. for the syrup: place all the syrup ingredients into a saucepan and bring to a gentle simmer. cook for 15 minutes, or until the liquid has reduced by one-third. stir occasionally, then leave to cool.
8. remove the baklava from the oven and spoon half the cooked syrup all over the top. leave for five minutes, then spoon over the remaining syrup. allow the baklava to cool completely before removing the individual pieces from the dish with a palette knife. serve.
