* Girdlebuster
@recipe @dessert

** Ingredients
/Base/

- 375g digestive biscuits
- 75g soft unsalted butter
- 50g dark chocolate pieces or chips
- 50g milk chocolate pieces or chips
- for the ice cream filling:
- 1 ltr ice cream(coffee, vanilla, chocolate)

/Topping/

- 300g golden syrup
- 100g light muscovado sugar
- 75g unsalted butter
- 2 x 15ml tablespoons bourbon
- 125ml double cream

** Method

1. process the biscuits with the butter and chocolate pieces or chips until it forms a damp but still crumb-like clump. press into a 23cm pie plate or flan dish. form a lip of biscuit a little higher than the plate or dish if you can. this process takes patience as you need ideally to form a smooth even layer. freeze this biscuit-lined layer for about an hour so it gets really hard
2. let your ice cream soften, just enough to be scooped, in the fridge. spread the ice cream into the hard-biscuit-lined dish to form a layer. then cover in clingfilm and replace in the freezer.
3. put the syrup, sugar, and butter into a saucepan and let it melt over a low to medium heat, before turning it up and boiling for 5 minutes, then turn off the heat and add the bourbon, letting it hiss in the pan. add the cream and stir to mix into a sauce, then leave to cool. once the sauce is cool, but not set cold, pour it over the pie to cover the ice cream layer and then put it back in the freezer. once frozen, cover with clingfilm again.
4. when ready to serve, remove from the freezer, take the whole pie out of its dish and cut into slices. should you have any pie left over, slip it quickly back into the dish and return, covered with clingfilm, to the freezer.
