* White Chocolate Mousse
@recipe @dessert

** Ingredients
Note:important to have ingredients at room temp to ensure texture is smooth.

- 100G white chocolate buttons
- 125ml skimmed milk
- 2 teaspoons gelatine
- 400g low fat French vanilla fromage frais
- 3 egg whites
- 3 tablespoons passionfruit pulp
- icing sugar to dust

** Method

1. place the chocolate and milk in a small saucepan and stir over low heat until the chocolate has melted. Allow to cool.
2. place 60ml boiling water in a small bowl, sprinkle evenly with gelatine and stir until dissolved.
3. using a wooden spoon, stir the gelatine into the chocolate mixture.
4. place the fromage frais in a large bowl and gradually stir in the chocolate mixture a little at a time stirring until smooth after each addition.
5. beat the egg whites in a clean dry bowl with electric beaters until soft peaks form.
6. gently fold the egg whites and passionfruit pulp into the chocolate mixture.
7. divide mixture evenly into serving glasses or a glass bowl.
8. refrigerate for 3 hours or until set.
9. serve with a light dusting of icing sugar.
