#+TITLE: Naan Bread
#+ROAM_TAGS: @recipe @bread

* Ingredients

- 2 teaspoon sugar
- 1teaspoon fresh yeast
- 150ml warm water
- 200g plain flour
- 1 tablespoon ghee
- 1 teaspoon salt
- 50g unsalted butter
- 1 teaspoon poppy seed

* Method

1. put sugar and yeast in a small bowl with warm water and mix well until dissolved. set aside for 10mins or until mix is frothy
2. place the flour ina large mixing bowl, make a well in the middle of the flour. add the ghee and salt and pour in the yeast mixture. mix well to form a dough, using your hands. adding more water if required
3. turn the dough onto a floured surface and knead for 5 mins until smooth
4. return the dough to the bowl cover and leave to rise in a warm place for 11/2 hours or until doubled in size
5. turn the dough onto a floured surface and knead for a further 2 mins. break off small balls with your hand and pat into rounds about 12cm dia and 1 cm thick
6. place the dough rounds onto a greased sheet of foil and grill under a preheated grill for 7-10 mins, turning twice and brushing with the butter and sprinkling with the poppy seeds
7. serve warm immediately or keep wrapped in foil
