* Vegetarian recipe ideas
  :PROPERTIES:
  :CUSTOM_ID: vegetarian-recipe-ideas
  :END:

- pasta & pesto
- stuffed peppers
- thai red curry with lots of veg
- lentil and bean chilli
- black bean and sweet potato enchiladas
- huevos rancheros
- bean, avocado, coriander, charred tomato, and corn salad
- quinoa bowl with sliced avocado, tomato, beans, and friend egg

** Foods every vegetarian should eat
   :PROPERTIES:
   :CUSTOM_ID: foods-every-vegetarian-should-eat
   :END:

*Tofu* - Protein, zinc, iron, calcium. You can substitute meat with the
same amount of tofu in almost any recipe. Firm tofu works best, as it
holds its shape.

*Lentils* - Part of the legume family, like beans. Excellent source of
protein and soluble fibre, but they carry about twice as much iron as
beans. Also tend to be less gassy. Add lentils to stews, chillis,
casseroles, soups. Toss them with red onions and vinaigrette. Stir into
curries; cook with carrots.

*Beans* - Great source of iron, protein, and fiber. Rinse well, as they
can be soaked in salt.

*Nuts* - Quick, palatable protein. Walnuts, peanuts, almonds, cashews,
pecans, macademias, and brazils are rich in zinc, vitamin E, and omega3
fatty acids. Some research suggests that eating a nut-high diet doesn't
lead to weight gain, even though they are very calorie dense.
Potentially they make you feel full so you don't overeat other things.

*Grains* - some enriched whole-grain cereals are fortified with the B12
that you often lack in a vegetarian diet. However, if you don't eat eggs
or dairy you'll likely need a B12 supplement. Think whole-wheat breads
and pastas, brown rice etc. Different grains provide different
nutrients, so /mix it up/. Oatmeal, bulgur, wild rice, whole rye and
pumpernickel breads. Spelt, farro, kamut.

*Leafy greens* - Spinach, broccoli, kale, swiss chard, and collards.
Contains healthy amounts of iron (especially spinach). Try to eat them
with VitaminC rich food, as these help your body absorb the iron.

*Seaweeds* - Great source of iron and phytochemicals. Also good source
of minerals. Chop and add to salads and sandwiches. Saute with other
veg. Use in soups.

*Dried fruits* - super-convenient sources of iron. If you combine with
mixed nuts, you've got a packet of iron and protein you can take
anywhere.
