#+TITLE: Chilli Non-Carne Soup
#+ROAM_TAGS: @recipe @soup

~serves 6 ~40 minutes

* Ingredients

- olive oil 2 tbsp
- garlic 4 cloves,crushed
- onions 2,chopped
- celery 2 stalks,diced
- yellow pepper 1,cut into small chunks
- mild chilli powder 1 tbsp
- ground cumin 2 tsp
- balsamic vinegar 1 tbsp
- brown sugar 1 tbsp
- chopped tomatoes 400g tin
- vegetable stock 500ml
- kidney beans 400g tin,drained and rinsed
- garlic baguette 1
- mature cheddar 100g,grated
- spring onions 3,chopped

* Method

1. Heat the olive oil in a large pan and fry the garlic, onions and celery for 10 minutes or until softened. Add the pepper and cook for 5 minutes, then stir in the chilli powder and cumin. Cook for a few minutes, then add the balsamic, sugar, tomatoes, stock and some seasoning. Simmer for 10 minutes.
2. Add the kidney beans and cook for 10 minutes. Meanwhile, heat the baguette in the oven following pack instructions. Sprinkle the soup with the cheese and spring onions, and serve with the hot garlic baguette.

#vegetarian
