* Potato and Mushroom Stew
@recipe @soup

- Serves 4 [(originally made for 6, but fuck that...)]
- Cooking Time - 60 minutes
- roughly 500cal, 75g carbs, 15g fat, and 11g protein per serving

** Ingredients

- 1 tablespoon olive oil
- 6 garlic cloves, minced
- 1/2 teaspoon salt
- Pinch or two red pepper flakes
- About 1/4 teaspoon fresh black pepper
- 1/4 teaspoon smoked paprika
- 6 medium potatoes, cleaned and cut into bite-size chunks
- 1 teaspoon olive oil
- 4-5 medium/large Portobello/Cremini mushrooms, cut into thick slices
- 1 small onion, chopped
- 1 small red bell pepper, chopped
- 2 tablespoons olive oil
- 2 tablespoons gluten-free flour blend
- 4 cups unsweetened almond milk, divided
- 1/4 teaspoon salt
- Black pepper to taste

** Preparation

1.  Heat the oven to 375°F.
2.  Combine the tablespoon of olive oil, garlic, salt, red pepper flakes, black pepper, smoked paprika, and potatoes in a large mixing bowl and toss together until the potatoes are evenly coated.
3.  Turn out onto a baking sheet, making sure the potatoes are in a single layer. Roast for 30 minutes, stirring once.
4.  In the same bowl, combine the teaspoon of oil, mushrooms, onion, and bell pepper.
5.  When you take the potatoes from the oven, add them to the bowl and toss to combine.
6.  Dump the bowl back out onto the baking sheet and roast for 20 minutes, stirring once. Start the soup base so it's ready when the potatoes and vegetables are finished roasting.
7.  In a large, lidded pot combine the olive oil and gluten-free flour blend over medium-low heat. Cook and stir for about 2-3 minutes.
8.  Turn the heat to medium and stir in 2 cups almoPnd milk.
9.  Cook, stirring frequently, for about 10 minutes.
10. Add the last of the almond milk and continue to cook and stir for another 10 minutes.
11. Take the roasted potatoes and veggies out of the oven and stir them into the soup base. Save a few of the red pepper pieces for garnish if you like. Add more salt and pepper to taste.
12. Lid the pot, turn the heat to low and simmer for about 10 minutes, stirring occasionally. Serve hot. ## Nutritional Information

- ~1935 calories
- ~281g carbs
- ~70g fat
- ~45g protein
