#+TITLE: Beef Satay
#+ROAM_TAGS: @recipe @main

* Ingredients

- 500g beef fillet
- 2 garlic cloves crushed
- 1.5 teaspoons finely grated fresh root ginger
- 1 tablespoon soft light brown sugar
- 1 tablespoon dark soy sauce
- 1 tablespoon lime juice
- 2 teaspoons sesame oil
- 1 teaspoon ground coriander
- 1 teaspoon turmeric
- 1/2teaspoon chilli powder
- chopped cucumber and red pepper to serve

/Peanut sauce/

- 300ml coconut milk
- 8 tablespoons crunchy peanut butter
- 1/2small onion grated
- 2 teaspoons soft light brown sugar
- 1/2teaspoon chilli powder
- 1tablespoon dark soy sauce

* Method

1. cut the beef into 1 cm cubes and place in a large bowl
2. add the crushed garlic, grated ginger, sugar, soy sauce, lime juice, sesame oil, ground coriander, turmeric and chilli powder. mix together well to coat the pieces of meat evenly. cover and leave to marinate in the fridge for at least 2 hours or overnight.
3. for the peanut sauce, place all the Ingredients in a pan and stir over a medium heat until boiling. remove from the heat and keep warm
4. soak some skewers for 20 mins in cold water. thread with the beef. barbecue or cok under a preheated grill for 3-5 mins, turning often.serve with the sauce, cucumber and red pepper
