#+TITLE: Beef And Mushroom Stew With Mustard Mash
#+ROAM_TAGS: @recipe @main

* Ingredients

- 50g butter

- 2 onions sliced

- 450g shoulder steak trimmed and cut into chunks

- 25g plain flour seasoned with salt, pepper and 1 tablespoon paprika

- 1 tablespoon sunflower oil

- 100g streaky bacon cut into lardons

- 200g chestnut mushrooms halved

- 400ml bottle scottish ale or 200ml red wine and 200ml chicken stock

- fresh ground sea salt and pepper

- 2 tablespoons chopped fresh parsley

* Method

1. preheat oven to 150c
2. melt half the butter in a casserole and the onions and fry till golden
3. put the steak into a poly bag with the seasoned flour, toss until well coated
4. heat a large frying pan until very hot. add the sunflower oil and bacon and stir fry until golden brown. remove with a slotted spoon and add to the onions in the casserole. now add the mushrooms to the frying pan and brown for a couple of mins then add to the casserole. add the remaining butter to the frying pan and brown the beef well. transfer to the casserole
5. add the beer or stock mix to the frying pan,bring to the boil and scrape all the brown bits from the bottom of the pan to help flavour the sauce. pour this into the casserole, add plenty of seasoning especially pepper and mix together well
6. cover the casserole and bake for 1-11/2 hours.stir in the chopped parsley when ready to serve
7. check seasoning and serve with mashed potato with a tablespoon of whole grain mustard mixed through
