* Char-Siu Pork
@recipe @main

** Ingredients

- 500g pork fillet
- 150ml boiling water
- 1 tablespoon honey dissolved with a little hot water
- shredded lettuce to serve

/Marinade/

- 1 tablespoon sugar
- 1 tablespoon crushed yellow bean sauce
- 1 tablespoon light soy sauce
- 1 tablespoon hoi-sin sauce
- 1 tablespoon oyster sauce
- 1 teaspoon chilli sauce
- 1 tablespoon brandy or rum
- 1 teaspoon sesame oil

** Method

1. cut the pork into strips 2.5cm thick and 18-20 cm long and place in a large shallow [[http://dish.combine/][dish.combine]] the marinade Ingredients and add to the pork, turning until well coated. cover and leave to marinate for 3-4 hours or overnight turning occasionally
2. remove the pork strips from the dish with a slotted spoon, reserving the marinade.arrange the pork strips on a rack over a baking tin. place the baking tin in a preheated oven 220c and pour in the boiling water. roast for about 10-15 mins
3. lower the oven temp to 180c. baste the pork strips with the reserved marinade and turn. roast for a further 10 mins
4. remove the pork from the oven, brush with the honey syrup, and lightly brown under a grill for 3-4 mins, turning once or twice
5. to serve, alow the pork to cool slightly before cutting it. cut across the grain into thin slices and arrange on a bed of shredded lettuce. make a sauce by boiling the marinade and the drippings in the baking tin for a few minutes, strain and pour over the pork
