* Chicken Escalope

** Ingredients

- 4 chicken breasts, boned, skinned & pounded thin
- sea salt and freshly ground black pepper
- 2 eggs
- 1 tablespoon milk
- 60g plain flour
- 200g dry breadcrumbs
- olive oil
- 1 fresh ball of mozzarella
- 50g grated parmesan
- for the tomato sauce:
- olive oil
- 2 shallots
- 1 clove garlic, finely sliced
- approx 250g cherry tomatoes
- 1/2 teaspoon dried basil
- sea salt and freshly ground black pepper
- fresh basil to garnish

/For the potatoes/

- 500g potatoes, e.g. maris pipers
- 1 teaspoon chilli flakes

/For the chard/

- 2 garlic cloves, lightly crushed
- 600g baby red chard leaves

** Method

1. preheat the oven to 200°c.
2. peel and dice the potatoes. parboil the potatoes in salted water for
   5-6 minutes until just tender. drain well and set aside.
3. season the chicken fillets on both side with a little salt and
   pepper. lightly beat the eggs together with the milk. dust each
   chicken breast in flour, then dip in the beaten eggs and finally coat
   in the breadcrumbs.
4. sauté the escalopes in a little hot olive oil until golden brown -
   approximately 2 minutes on each side. drain the cooked chicken on
   kitchen paper, then remove to a baking tray.
5. to make the tomato sauce heat some oil in a heavy based pan. add the
   shallots and garlic and cook for 2-3 minutes until softened. add the
   tomatoes and basil. allow the tomatoes to soften. season to taste
   with salt and pepper.
6. spoon a little tomato sauce over each escalope. top with a round of
   mozzarella, and sprinkle with the grated parmesan. bake in the oven
   for approximately 8 minutes, until the chicken is cooked and the
   cheese is melted and golden.
7. drizzle with diced potatoes with oil and chilli flakes and season
   with salt and pepper. sauté in a hot pan until golden and cooked
   through.
8. heat a little olive oil in a hot pan, lightly sauté the garlic
   cloves, add the chard and toss. lightly sauté until the leaves are
   wilted, remove the garlic and drain on kitchen towel
9. serve each chicken escalope with a garnish of fresh basil, sautéed
   potatoes and a spoonful of sautéed chard.
