#+TITLE: Chicken Biryani
#+ROAM_TAGS: @recipe @main

* Ingredients

- 1tablespoon vegetable oil
- 2 garlic cloves crushed
- 2teaspoon finely grated root ginger
- 1 large onion finely chopped
- 350g chicken breast chunks
- 1/2teaspoon ground cinnamon
- 2teaspoon ground coriander
- 1teaspoon ground cumin
- 1/2teaspoon ground turmeric
- 225g basmati rice
- 90ml hot chicken stock
- 4 tomatoes cut into quarters
- salt and freshly ground black pepper
- 4 tablespoons plain yogurt to garnish
- fresh coriander to garnish

* Method

1. heat the oil in a large frying pan. add the garlic ginger and onion and saute gently for 2 mins
2. add the chicken. cook for 3-4 mins until browned. stir in the cinnamon, coriander, cumin, turmeric and rice. cook stirring for 1-2 mins
3. pour in the stock and add the tomatoes. cook over a low heat, stirring occasionally until the liquid has been absorbed and the rice is tender. if the rice is not tender when all the liquid has evaporated, add a little extra stock or water and cook for a few more minutes
4. season to taste with salt and pepper, then serve garnished with yogurt and chopped fresh coriander
