* Crispy Shredded Beef
@recipe @main

** Ingredients

- 350g beef steak
- 2 eggs
- 1/4teaspoon salt
- 4-5 tablespoon plain flour
- vegetable oil for deep frying
- 2 medium carrots shredded finely
- 2 spring onions shredded finely
- 1 clove of garlic chopped finely
- 2-3 small fresh red or green chilli seeded and shredded finely
- 4 tablespoon sugar
- 3 tablespoon rice vinegar
- 1 tablespoon light soy sauce
- 2-3 tablespoon chinese stock or water
- teaspoon cornflour paste

** Method

1. cut the steak across the grain into thin strips. beat the eggs in a bowl with the salt and flour, adding a little water as necessary. add the beef strips and mix well until coated with the batter
2. heat the oil ina preheated wok until smoking. add the beef strips and deep fry for 4-5 mins, stirring to separate the shreds. remove with a slotted spoon and drain on paper towel.
3. add the carrots to the wok and deep fry for 1-2 mins then remove and drain on paper towel
4. pour off the excess oil, leaving about 1 tablespoon in the wok. add the spring onion, garlic, chillis and carrot. stir fry for about 1 min. add the sugar, vinegar, soy sauce and stock or water, blend well and bring to the boil
5. stir in the cornflour paste and simmer for a few minutes to thicken the sauce. return the beef to the wok and stir until the shreds of meat are well coated with the sauce. serve hot
