* Five-Spice Lamb
@recipe @main

** Ingredients

- 625g lamb
- 2 teaspoon chinese 5 spice powder
- 3 tablespoon sunflower oil
- 1 red pepper cored seeded and thinly sliced
- 1 green pepper as above
- 1 yellow pepper as above
- 4-6 spring onion sliced thinly diagonally
- 175 green beans cut into 4cm lengths
- 2 tablspoon soy sauce
- 4 tablespoon sherry
- salt and pepper
- chinese noodles to serve
- strips of red and yellow pepper and fresh coriander to garnish

** Method

1. cut the lamb into narrow strips and place in a bowl. add the 5 spice powderand 1/4teaspoon salt. mix well and leave to marinate for a t least 1 hour or overnight covered
2. heat half the oil in a wok. add the lamb and stir fry briskly for 3-4 mins until almost cooked. remove from the pan.
3. add the remaining oil to the wok. when hot add the peppers and spring onions. stir fry for 2-3 mins. then add the beans and stir fry for a minute or so.
4. add the soy sauce and sherry to the wok and when hot replace the lamb and any juices. stir fry for 1-2 mins until the lamb is really hot again and thoroughly coated with the sauce. season to taste
5. serve with noodles garnished with strips of pepper and fresh coriander
