* Lamb Biryani
@recipe @main

** Ingredients

- 150ml milk
- 1 teaspoon saffron
- 5 tablespoons ghee
- 3 medium onions sliced
- 1kg of lean lamb cubed
- 7 tablespoons natural yogurt
- 11/2 teaspoon fresh root ginger finely chopped
- 11/2teaspoon fresh garlic crushed
- 2 teaspoon garam masala
- 2 teaspoon salt
- 1/4teaspoon turmeric
- 600ml water
- 450g basmati rice
- 2 teaspoon black cumin seed
- 3 cardamoms
- 4 tablespoon lemon juice
- 2 fresh green chilli
- 1/4 bunch fresh coriander

** Method

1. boil the milk in a pan with the saffron and set aside. heat the ghee in a pan, add the onion and fry until golden. remove 1/2the onion and ghee from the pan and set aside.
2. combine the meat, yogurt, ginger, garlic, garam masala, 1 teaspoon salt and turmeric in a large bowl
3. return the pan with ghee and onions to the heat, add the meat mixture, stir for 3 mins and add the water. cook on low heat for 45 mins stirring occasionally. if the meat is not tender, add 150ml of water and cook for 15mins. once the water has evaporated stir fry for 2 mins and set aside
4. meanwhile place the rice in a pan. add the cumin seed, cardamoms, salt and enough water for cooking and cook over a medium heat until the rice is half cooked. drain. remove half of the rice
5. spoon the meat mixture on top of the rice in the pan. add half each of the saffron milk, lemon juice, chillis and coriander. add the reserved onion and ghee mixture, the other half of the rice and other Ingredients. Cover and cook over a low heat for 15-20 mins.
