#+TITLE: Red Hot Beef with Cashews
#+ROAM_TAGS: @recipe @main

* Ingredients

- 500g lean beef sirloin thinly sliced
- 1 teaspoon vegetable oil

/Marinade/

- 1 tablespoon sesame seed
- 1 garlic clove crushed
- 1 tablespoon fresh root ginger finely chopped
- 1 red chilli chopped
- 2 tablespoon dark soy sauce
- 1 teaspoon red curry paste

/To finish/

- 1 teaspoon sesame oil
- 4 tablespoon unsalted cashew nuts
- 1 spring onion thickly sliced diagonally
- cucumber slices to garnish

* Method

1. cut the beef into 1 cm wide strips and place in a non metallic bowl
2. toast the sesame seeds in a heavy based pan on a medium heat for 2-3 mins until golden brown shaking the pan occasionally
3. place the seeds in a pestle and mortar with the garlic, ginger and chilli and grind to a smooth paste. add the soy sauce and curry paste and mix well
4. spoon the paste over the beef strips and toss well to coat the meat evenly. cover and leave to marinate in the fridge for 2-3 hours or overnight
5. heat a heavy frying pan or griddle until very hot and brush with vegetable oil. add the beef strips and cook quickly turning often until lightly browned. remove from the heat and spoon onto a hot serving dish
6. heat the sesame oil in a small pan and quickly fry the cashew nuts until golden. take care they do not burn. add the spring onion and stir fry for 30 secs. sprinkle the mixture over the beef strips and serve immediately garnished with cucumber slices
