* Vegetarian Lasagna
@recipe @main @vegetarian

** Ingredients

- 1 small aubergine, sliced and chopped
- 300g mushrooms, roughly chopped
- 3 tbsp vegetable oil
- 1 onion, finely chopped
- 3 cloves garlic, finely chopped
- 1x 400g tin tomatoes
- 200g roasted peppers from a jar, drained and sliced
- 35g unsalted butter
- 40g plain flour
- 300ml semi-skimmed milk
- 150g spinach
- 20g cheddar, grated
- 85g lasagna sheets (or enough for 2 layers)
- black pepper

** Method

1. Preheat oven to 200C (Fan 180C)
2. Place aubergine and mushrooms in a roasting tray. Drizzle with 2 tbsp oil to ensure veg are well coated. Roast for 45 min (till golden brown and soft)
3. Heat remaining oil in a frying pan over a medium-high heat and add onion. Saute for 5 minutes. Turn down heat and add garlic. Cook for a further 2-3 minutes, stirring regularly to ensure it doesn't burn.
4. Add tinned tomatoes and roasted peppers, seasoned with black pepper. Leave to simmer for 10-15 minutes
5. Meanwhile, melt butter in another pan over a medium heat. Add the flour and stir well. Cook for 1-2 minutes and then start adding milk, bit by bit, stirring to avoid lumps.
6. If using fresh spinach, wilt (place in a bowl and microwave for 1-2 min, or in a covered pan)

...

- mix the veg (onion, spinach, tomatoes, peppers, aubergine, and mushrooms)
- layer: veg, sheet, white sauce, cheese -- repeat
- top layer of lasagna sheet with grated cheese
- cover with foil and bake for ~20 minutes. remove foil towards the end and bake for another 5-10 minutes

Allow to sit in the pan for 10 min before serving
