#+TITLE: Broccoli Fritters
#+ROAM_TAGS: @starter @recipe @side

* Ingredients

- 6-7 broccoli stems, shredded (about 1.5-2 cups)
- 2 eggs, whisked
- 1 3/4 cup almond meal
- 1/2 sweet onion, finely chopped
- 1 tablespoon garlic powder
- 1 teaspoon minced garlic
- lots of salt and pepper

* Method

1. Send your broccoli stems through a shredder. I used a food processor with the shredding attachment which made it go by super fast.
2. Add your shredded broccoli to a large bowl along with all other ingredients and mix well.
3. Heat up a large skillet over medium-high heat with a bit of fat in it. Use a large spoon and your hands to ball up a fritter and add to a skillet. It doesn't need to be flat, you'll flatten it out after you flip it.
4. Cook the fritter for about 3-4 minutes, then use a spatula to flip, then flatten out with the spatula. Cook for another 4 minutes or so.
5. Once the fritters are crisp on both sides, eat them. I topped mine with a grass fed beef burger.

[[http://paleomg.com/paleo-broccoli-fritters/]]
