#+TITLE: Hummus
#+ROAM_TAGS: @recipe @side

* Ingredients

- 200g dried chickpeas
- 2 large garlic cloves
- 7 tablespoons extra virgin oil
- 2.5 tablespoon tahini
- 1 tablespoon lemon jui ce or to taste
- salt and pepper
- to garnish
- extra virgin olive oil
- paprika
- fresh coriander

* Method

1. place the chickpeas in a large bowl.pour in at least twice the volume of cold water to beans and leave to stand for at least 12 hours until they double in size
2. drain the chickpeas.put them in a large saucepan and add twice the volume of water to beans.bring to boil and boil hard for 10 minutes skimming the surface of the liquid
3. lower the heat and simmer for 1 hour skimming the surface if required until the chickpeas are tender. cut the garlic cloves in half. discard the pale green or white cores and coarsely chop.set aside
4. drain the chick peas reserving about 4 tablespoons of the cooking liquid.put the olive oil,garlic,tahini and lemon juice in a food processor and blend until a smooth paste forms
5. add the chick peas and pulse until they are finely ground but the hummus is still slightly textured. add a little of the reserved cooking liquid if the mixture is too thick
6. transfer to a bowl,cover with cling film and chill until ready to serve.
7. to serve,drizzle with some olive oil,sprinkle with a little paprikaand garnish with fresh coriander.
8. serve with pitta bread
